version: "2"
services:
  web:
    build:
      context: ./
      dockerfile: docker/nginx.docker
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
    links:
      - app
  app:
    build:
      context: ./
      dockerfile: docker/php.docker
    volumes:
      - ./:/var/www